root: true
env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - google
  - plugin:import/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:import/typescript
  - prettier
  - eslint-config-prettier
plugins:
  - prettier
  - eslint-plugin-tsdoc
  - '@typescript-eslint'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  createDefaultProgram: true
  project: ./tsconfig.json
rules:
  new-cap: off
  no-invalid-this: off
  no-unused-vars: warn
  prettier/prettier: error
  require-jsdoc: warn
  valid-jsdoc: off
settings:
  import/resolver:
    typescript: {}
    alias:
      map:
        - ['@', './src']
      extensions:
        - .js
        - .ts
        - .jsx
        - .tsx
