env:
  browser: true
  es2021: true
  node: true
extends:
  - standard-with-typescript
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - eslint-config-prettier
overrides: []
plugins:
  - tsdoc
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  createDefaultProgram: true
  project:
    - ./tsconfig.app.json
    - ./tsconfig.node.json
rules:
  require-jsdoc: warn
  no-unused-vars: warn
  '@typescript-eslint/ban-ts-comment': off
  '@typescript-eslint/no-confusing-void-expression': off
  '@typescript-eslint/no-floating-promises': off
  '@typescript-eslint/no-invalid-void-type': off
  '@typescript-eslint/prefer-nullish-coalescing': off
  '@typescript-eslint/strict-boolean-expressions': off
  '@typescript-eslint/triple-slash-reference': off
  '@typescript-eslint/restrict-template-expressions': off
  tsdoc/syntax: warn
settings:
  import/parsers:
    '@typescript-eslint/parser':
      - .ts
      - .tsx
  import/resolver:
    typescript: {}
    alias:
      map:
        - ['@', './src']
      extensions:
        - .js
        - .ts
        - .jsx
        - .tsx
  vite:
    configPath: ./vite.config.ts
