env:
  browser: true
  es2022: true
  node: true
extends:
  - standard-with-typescript
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:yaml/recommended
  - eslint-config-prettier
overrides: []
plugins:
  - tsdoc
rules:
  require-jsdoc: warn
  no-unused-vars: warn
  '@typescript-eslint/triple-slash-reference': off # for vite fix
  '@typescript-eslint/strict-boolean-expressions': off # for vite fix
  tsdoc/syntax: warn
parserOptions:
  ecmaVersion: latest
  sourceType: module
  createDefaultProgram: true
  project:
    - ./tsconfig.app.json
    - ./tsconfig.node.json
settings:
  import/parsers:
    '@typescript-eslint/parser':
      - .ts
      - .tsx
  import/resolver:
    typescript: true
    alias:
      map:
        - ['@', './src']
        - ['~', './node_modules']
      extensions:
        - .js
        - .ts
        - .jsx
        - .tsx
  vite:
    configPath: ./vite.config.ts
