printWidth: 80
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
trailingComma: es5
bracketSpacing: true
bracketSameLine: false
arrowParens: avoid
htmlWhitespaceSensitivity: ignore
endOfLine: lf
# plugins:
#   - prettier-plugin-jsdoc
#   - prettier-plugin-md-nocjsp
#   - prettier-plugin-sort-imports
