allowBuilds:
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@biomejs/biome@2.5.1'
  - '@biomejs/cli-darwin-arm64@2.5.1'
  - '@biomejs/cli-darwin-x64@2.5.1'
  - '@biomejs/cli-linux-arm64-musl@2.5.1'
  - '@biomejs/cli-linux-arm64@2.5.1'
  - '@biomejs/cli-linux-x64-musl@2.5.1'
  - '@biomejs/cli-linux-x64@2.5.1'
  - '@biomejs/cli-win32-arm64@2.5.1'
  - '@biomejs/cli-win32-x64@2.5.1'
  - '@rsbuild/core@2.1.0 || 2.1.1'
  - '@rspack/binding-darwin-arm64@2.1.0 || 2.1.1'
  - '@rspack/binding-darwin-x64@2.1.0 || 2.1.1'
  - '@rspack/binding-linux-arm64-gnu@2.1.0 || 2.1.1'
  - '@rspack/binding-linux-arm64-musl@2.1.0 || 2.1.1'
  - '@rspack/binding-linux-riscv64-gnu@2.1.0 || 2.1.1'
  - '@rspack/binding-linux-riscv64-musl@2.1.0 || 2.1.1'
  - '@rspack/binding-linux-x64-gnu@2.1.0 || 2.1.1'
  - '@rspack/binding-linux-x64-musl@2.1.0 || 2.1.1'
  - '@rspack/binding-wasm32-wasi@2.1.0 || 2.1.1'
  - '@rspack/binding-win32-arm64-msvc@2.1.0 || 2.1.1'
  - '@rspack/binding-win32-ia32-msvc@2.1.0 || 2.1.1'
  - '@rspack/binding-win32-x64-msvc@2.1.0 || 2.1.1'
  - '@rspack/binding@2.1.0 || 2.1.1'
  - '@rspack/core@2.1.0 || 2.1.1'
  - prettier@3.8.5
  - '@rslib/core@0.23.1'
  - rsbuild-plugin-dts@0.23.1
onlyBuiltDependencies:
  - unrs-resolver
