import { fileURLToPath, URL } from 'node:url';
import { writeFileSync } from 'node:fs';

import { checker } from 'vite-plugin-checker';
import { defineConfig, type UserConfig } from 'vite';
import { visualizer } from 'rollup-plugin-visualizer';
import banner from 'vite-plugin-banner';
import dts from 'vite-plugin-dts';

// @ts-expect-error
import pkg from './package.json';

// Export vite config
export default defineConfig(async ({ command, mode }): Promise<UserConfig> => {
  // Hook production build.
  // https://vitejs.dev/config/
  const config: UserConfig = {
    plugins: [
      // vite-plugin-checker
      // https://github.com/fi3ework/vite-plugin-checker
      checker({
        typescript: true,
        vueTsc: false,
        eslint: {
          lintCommand:
            'eslint ./src --fix --cache --cache-location ./node_modules/.vite/vite-plugin-eslint',
        },
      }),
      // vite-plugin-banner
      // https://github.com/chengpeiquan/vite-plugin-banner
      banner(`/**
 * ${pkg.name}
 *
 * @description ${pkg.description}
 * @author ${pkg.author.name} <${pkg.author.email}>
 * @copyright 2019-2023 By Masashi Yoshikawa All rights reserved.
 * @license ${pkg.license}
 * @version ${pkg.version}
 * @see {@link ${pkg.homepage}}
 */
`),
      // vite-plugin-dts
      // https://github.com/qmhc/vite-plugin-dts
      mode === 'docs'
        ? undefined
        : dts({
            tsConfigFilePath: './tsconfig.app.json',
          }),
    ],
    // https://vitejs.dev/config/shared-options.html#publicdir
    publicDir: mode === 'docs' || command === 'serve' ? 'public' : false,
    // https://vitejs.dev/config/#server-options
    server: {
      fs: {
        // Allow serving files from one level up to the project root
        allow: ['..'],
      },
    },
    // Build Options
    // https://vitejs.dev/config/#build-options
    build: {
      outDir: mode === 'docs' ? 'docs' : 'dist',
      lib:
        mode === 'docs'
          ? false
          : {
              entry: fileURLToPath(new URL('src/Reverb.ts', import.meta.url)),
              name: 'Reverb',
              formats: ['es', 'umd', 'iife'],
              fileName: format => `Reverb.${format}.js`,
            },
      rollupOptions: {
        plugins: [
          mode === 'analyze'
            ? // rollup-plugin-visualizer
              // https://github.com/btd/rollup-plugin-visualizer
              visualizer({
                open: true,
                filename: './stats.html',
                gzipSize: false,
                brotliSize: false,
              })
            : undefined,
        ],
        external:
          mode === 'docs'
            ? []
            : [
                '@thi.ng/colored-noise',
                '@thi.ng/random',
                '@thi.ng/transducers',
              ],
        output: {
          globals: {
            '@thi.ng/colored-noise': 'colordNoise',
            '@thi.ng/random': 'random',
            '@thi.ng/transducers': 'transducers',
          },
        },
      },
      target: 'esnext',
      minify: false,
    },
    esbuild: {
      drop: command === 'serve' ? [] : ['console'],
    },
  };
  // Write meta data.
  writeFileSync(
    fileURLToPath(new URL('src/Meta.ts', import.meta.url)),
    `import type MetaInterface from './interfaces/MetaInterface';

// This file is auto-generated by the build system.
const meta: MetaInterface = {
  version: '${pkg.version}',
  date: '${new Date().toISOString()}',
};
export default meta;
`
  );

  return config;
});
