import * as webpack from 'webpack';
import * as path from 'path';
import * as fs from 'fs';
import * as TerserPlugin from 'terser-webpack-plugin';

const pjson = require('./package.json');
const build: string = new Date().toISOString();

fs.writeFileSync(
  path.resolve(path.join(__dirname, 'src/meta.ts')),
  `const Meta = {
  // This file is auto-generated by the build system.
  version: '${pjson.version}',
  date: '${build}',
};
export default Meta;
`
);

const defaultEnvironment = {
  production: false,
  watch: false,
  analyze: false,
};

module.exports = (env = defaultEnvironment) => {
  const isProduction = env && env.production;
  const banner = `${pjson.name} v${pjson.version} | ${pjson.author.name} | license: ${pjson.license} | build: ${build}`;

  return {
    mode: env,
    target: 'node',
    devtool: !isProduction ? 'source-map' : false,
    devServer: {
      contentBase: 'docs',
      open: false,
    },
    entry: {
      reverb: './src/Reverb.ts',
    },
    output: {
      path: path.resolve(__dirname, 'bin'),
      filename: !isProduction ? '[name].js' : '[name].min.js',
      library: 'Reverb',
      libraryTarget: 'umd',
      umdNamedDefine: true,
      globalObject: "(typeof self !== 'undefined' ? self : this)",
    },
    optimization: {
      minimize: isProduction,
      minimizer: [
        new TerserPlugin({
          terserOptions: {
            ecma: 2020,
            compress: {drop_console: true},
            output: {
              comments: false,
              beautify: false,
            },
          },
        }),
      ],
      splitChunks: {
        minSize: 0,
      },
      concatenateModules: false,
    },
    module: {
      rules: [
        {
          test: /\.js/,
          exclude: /node_modules/,
          use: [
            {
              loader: 'source-map-loader',
            },
          ],
        },
        {
          test: /\.tsx?$/,
          loader: 'ts-loader',
        },
      ],
    },
    resolve: {
      modules: [`${__dirname}/src`, 'node_modules'],
      extensions: ['webpack.ts', '.ts', '.tsx', '.js'],
    },
    plugins: [
      new webpack.BannerPlugin({
        banner: banner,
      }),
    ],
  };
};
