/* eslint-disable @typescript-eslint/no-explicit-any */
import webpack = require('webpack');
import * as path from 'path';
import * as fs from 'fs';
import TerserPlugin from 'terser-webpack-plugin';
import WebpackDevServer from 'webpack-dev-server';

declare module 'webpack' {
  interface Configuration {
    /**
     * Can be used to configure the behaviour of webpack-dev-server when
     * the webpack config is passed to webpack-dev-server CLI.
     */
    devServer?: WebpackDevServer.Configuration;
  }
}

// バージョン情報など
const pjson = require('./package.json');
// 現在の時刻（ビルド時刻）
const build: string = new Date().toISOString();

module.exports = (_env: any, argv: any): webpack.Configuration => {
  const isProduction: boolean = argv.mode === 'production';
  if (isProduction) {
    // Meta.tsを書き込む
    fs.writeFileSync(
      path.resolve(path.join(__dirname, 'src/Meta.ts')),
      `import MetaInterface from './interfaces/MetaInterface';

// This file is auto-generated by the build system.
const meta: MetaInterface = {
  version: '${pjson.version}',
  date: '${build}',
};
export default meta;
`
    );
  }
  const banner = `${pjson.name} v${pjson.version} | ${pjson.author.name} | license: ${pjson.license} | build: ${build}`;

  return {
    mode: isProduction ? 'production' : 'development',
    target: 'node',
    devtool: !isProduction ? 'source-map' : false,
    devServer: {
      static: {
        directory: 'docs',
        watch: true,
      },
      open: false,
      hot: false,
    },
    entry: {
      reverb: './src/Reverb.ts',
    },
    output: {
      path: path.resolve(__dirname, 'bin'),
      filename: !isProduction ? '[name].js' : '[name].min.js',
      library: 'Reverb',
      libraryTarget: 'umd',
      umdNamedDefine: true,
      globalObject: "(typeof self !== 'undefined' ? self : this)",
    },
    optimization: {
      minimize: isProduction,
      minimizer: [
        new TerserPlugin({
          terserOptions: {
            ecma: 2020,
            compress: {drop_console: true},
            output: {
              comments: false,
              beautify: false,
            },
          },
        }),
      ],
      splitChunks: {
        minSize: 0,
      },
      concatenateModules: false,
    },
    module: {
      rules: [
        {
          test: /\.tsx?$/,
          loader: 'ts-loader',
        },
      ],
    },
    resolve: {
      modules: [`${__dirname}/src`, 'node_modules'],
      extensions: ['webpack.ts', '.ts', '.tsx'],
    },
    plugins: [
      new webpack.BannerPlugin({
        banner: banner,
      }),
    ],
  };
};
