import MetaInterface from './interfaces/MetaInterface';

// This file is auto-generated by the build system.
const meta: MetaInterface = {
  version: '0.3.0',
  date: '2020-11-05T05:45:14.799Z',
};
export default meta;
