import MetaInterface from './interfaces/MetaInterface';

// This file is auto-generated by the build system.
const meta: MetaInterface = {
  version: '0.4.0',
  date: '2020-12-28T13:57:49.017Z',
};
export default meta;
