import MetaInterface from './interfaces/MetaInterface';

// This file is auto-generated by the build system.
const meta: MetaInterface = {
  version: '0.4.1',
  date: '2021-05-28T08:55:41.505Z',
};
export default meta;
